[edge_compute]
func_id = "8a749e5c-8e44-414d-8200-fa9c42687cfc"
func_name = "telnyx-edge"

# For environment variables and secrets:
# Use telnyx-edge secrets add <name> <value>
# Secrets are injected as environment variables into all your functions
[storage.kv.SPA_DATA]
id = "df5b1882-e055-488a-924a-63f6e16c7abc"


